baseurl = "https://museeblog.at/"
title = "MuséeBlog"
canonifyurls = true
languagecode = "de-DE"
summaryLength = 25
enableEmoji = true
paginate = 6
enableRobotsTXT= true
description = "Mein Blog gefüllt mit Erlebnisberichten zu Ausflügen, Ausstellungen und Museen. Manchmal schreib ich auch Geschichten. Schau ihn dir an."

[author]
    name = "Muséedepot"
    mail = "museedepot@protonmail.com"
    github = "museedepot/museeblog"
    #gitlab = ""
    #linkedin = ""
    paypal = "https://paypal.me/museedepot?locale.x=de_DE"
    #twitter = ""
    #instagram = ""
    #mastodon = ""
    #patreon = ""

[params]
    tagline = "Ausflüge, Austellungen, Museen, Geschichten"
