baseurl = "https://museeblog.at/"
title = "MuséeBlog | Blog, Museen & Ausflüge"
canonifyurls = true
languagecode = "de"
summaryLength = 25
enableEmoji = true
paginate = 6
enableRobotsTXT= true
DefaultContentLanguage = "de"
footnoteReturnLinkContents = "↩"



[author]
    name = "Muséeblog"
    mail = "museedepot@protonmail.com"
    github = "museedepot/museeblog"
    #gitlab = ""
    #linkedin = ""
    paypal = "https://paypal.me/museedepot?locale.x=de_DE"
    #twitter = ""
    #instagram = ""
    #mastodon = ""
    #patreon = ""

[params]


[languages.de]
weight = 0
languageName = "Deutsch"
tagline = "Ausflüge, Ausstellungen, Museen, Geschichten"

[[languages.de.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[languages.en]
weight = 10
languageName = "English"
tagline = "trips, exhibtions, museums, stories"

[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  fractions = false

[sitemap]
  changefreq = "weekly"
  priority = 0.5
